import { useEffect, useRef, useState } from 'react'
import { motion } from 'framer-motion'

// Images live in public/anime/ and are listed in public/anime/manifest.json
// (generated by scripts/gen-anime-manifest.mjs on predev/prebuild). Nothing is
// bundled, so the folder can hold thousands of images without bloating the build.
//
// Only WINDOW cards are ever mounted, so only ~WINDOW images are ever fetched —
// swiping recycles the front card to the back with the next image from the pool.
// This is what keeps a huge folder from loading every image at once.
const WINDOW = 5
const MANIFEST = `${import.meta.env.BASE_URL}anime/manifest.json`
const tilts = [-3, 4, -5, 3, -2, 5]
const SWIPE_THRESHOLD = 100

function shuffle(arr) {
  const a = arr.slice()
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

export default function QuoteDeck() {
  const [urls, setUrls] = useState([])       // full shuffled pool of image URLs
  const [cards, setCards] = useState([])     // ≤ WINDOW visible cards, back(0) → front(last)
  const cursor = useRef(0)                    // next pool index to reveal
  const nextKey = useRef(0)                   // monotonic React keys

  // Load the manifest once, seed the initial window.
  useEffect(() => {
    let alive = true
    fetch(MANIFEST)
      .then((r) => (r.ok ? r.json() : []))
      .then((names) => {
        if (!alive || !Array.isArray(names)) return
        const pool = shuffle(names).map((n) => `${import.meta.env.BASE_URL}anime/${n}`)
        setUrls(pool)
        const seed = pool.slice(0, WINDOW).map((url) => ({ key: nextKey.current++, url }))
        setCards(seed)
        cursor.current = pool.length ? seed.length % pool.length : 0
      })
      .catch(() => {})
    return () => {
      alive = false
    }
  }, [])

  // Move the front card to the back keeping its image (so the snap-back stays
  // smooth), then — once it's parked behind the stack and invisible — swap in the
  // next pool image. Preload it first so it's ready when it surfaces.
  // const sendToBack = () => {
  //   if (!urls.length) return
  //   let movedKey
  //   setCards((cs) => {
  //     if (cs.length < 2) return cs
  //     const front = cs[cs.length - 1]
  //     movedKey = front.key
  //     return [front, ...cs.slice(0, -1)]
  //   })
  //   if (movedKey === undefined) return
  //   const url = urls[cursor.current % urls.length]
  //   cursor.current = (cursor.current + 1) % urls.length
  //   const pre = new Image()
  //   pre.src = url
  //   window.setTimeout(() => {
  //     setCards((cs) => cs.map((c) => (c.key === movedKey ? { key: nextKey.current++, url } : c)))
  //   }, 420)
  // }
  // Move the front card to the back and give it the next image.
  const sendToBack = () => {
    if (!urls.length) return

    const url = urls[cursor.current % urls.length]
    cursor.current = (cursor.current + 1) % urls.length

    setCards((cs) => {
      if (cs.length < 2) return cs

      const front = cs[cs.length - 1]

      return [
        { key: nextKey.current++, url },
        ...cs.slice(0, -1),
      ]
    })
  }

    // No images yet...
  if (!cards.length) {
    // No images yet (empty manifest / fetch failed) — friendly placeholder.
    return (
      <div className="flex h-[400px] w-[300px] items-center justify-center rounded-3xl glass-strong text-center text-sm text-textMuted sm:w-[340px]">
        Drop anime images into
        <br />
        <code className="text-red">public/anime/</code>
      </div>
    )
  }

  return (
    <div className="relative h-[400px] w-[300px] select-none sm:w-[340px]">
      {cards.map((c, i) => {
        const depth = cards.length - 1 - i // 0 = front
        const isFront = depth === 0
        return (
          <motion.div
            key={c.key}
            className="absolute inset-0"
            style={{ zIndex: i }}
            animate={{
              y: depth * -12,
              scale: 1 - depth * 0.05,
              rotate: isFront ? 0 : tilts[depth % tilts.length],
              opacity: depth > 3 ? 0 : 1,
            }}
            transition={{ type: 'spring', stiffness: 300, damping: 30 }}
          >
            <motion.article
              className="relative h-full w-full overflow-hidden rounded-3xl bg-surface2 shadow-2xl ring-1 ring-borderStrong"
              style={{ cursor: isFront ? 'grab' : 'default' }}
              drag={isFront}
              dragSnapToOrigin
              dragElastic={0.7}
              whileDrag={{ cursor: 'grabbing', scale: 1.03 }}
              onDragEnd={(e, info) => {
                if (
                  Math.abs(info.offset.x) > SWIPE_THRESHOLD ||
                  Math.abs(info.offset.y) > SWIPE_THRESHOLD ||
                  Math.abs(info.velocity.x) > 500
                ) {
                  sendToBack()
                }
              }}
            >
              {/* Blurred backdrop fills the frame so any aspect ratio letterboxes cleanly */}
              <img
                src={c.url}
                alt=""
                aria-hidden
                loading="lazy"
                decoding="async"
                className="absolute inset-0 h-full w-full scale-110 object-cover opacity-40 blur-2xl"
              />
              <div className="absolute inset-0 bg-bgDeep/30" />
              {/* Full image, never cropped */}
              <img
                src={c.url}
                alt="anime quote"
                draggable={false}
                loading="lazy"
                decoding="async"
                className="relative z-10 h-full w-full object-contain p-2"
              />
            </motion.article>
          </motion.div>
        )
      })}
    </div>
  )
}
